eksctl create cluster \
--name ClusterGit \
--region eu-west-2 \
--nodegroup-name DemoNodes \
--nodes 8 \
--nodes-min 2 \
--nodes-max 10 \
--node-type t3.medium \
--with-oidc \
--ssh-access \
--ssh-public-key AMSkey \
--managed
